# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: db_user
      POSTGRES_DB: db_name
      
    django_gunicorn:
      volumes:
        - static:/static
      env_file:
        - .env
      build:
        context: .
      ports:
        - "8000:8000"
    nginx:
      build: ./nginx
      volumes:
        - static:/static
      ports:
        - "80:80"
      depends_on:
        - django_gunicorn


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
