# Generated by Django 3.2.6 on 2021-08-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Nomre')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('adress', models.CharField(max_length=255, verbose_name='Adresimiz')),
                ('about', models.TextField(verbose_name='Haqqimizda')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
