# Generated by Django 3.2.6 on 2021-08-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koderapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='adress',
            new_name='address',
        ),
    ]
