# Generated by Django 3.2.6 on 2021-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koderapp', '0004_auto_20210822_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoding',
            name='img',
            field=models.ImageField(upload_to='media/', verbose_name='Sekil'),
        ),
    ]
