# Generated by Django 3.2.6 on 2021-08-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koderapp', '0005_alter_incoding_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='media/', verbose_name='Sekil'),
        ),
    ]
