# Generated by Django 3.2.6 on 2021-08-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koderapp', '0006_alter_project_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Sekil'),
        ),
    ]
