# Generated by Django 3.2.6 on 2021-08-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koderapp', '0007_alter_project_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incoding',
            name='img',
        ),
    ]
